project:
  type: website
  output-dir: docs
  resources:
    - assets/logo_header.svg
  render:
    - index.qmd
    - por/index.Rmd
    - por/*.qmd
    - por/tutorial/*.qmd
    - eng/*.qmd
    - eng/tutorial/*.qmd

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

lang: pt

website:
  title: "CancerTrialsBR"
  favicon: assets/favicon.ico
  navbar:
    logo: "assets/logo_header.svg"
    title: false
    search: false
    right:
      - href: por/index.Rmd
        text: "🇧🇷 Português"
      - href: eng/index.qmd
        text: "🇺🇸 English"
      - icon: github
        href: "https://github.com/felippelazar/CancerTrialsBR"
  page-navigation: true
  sidebar:
    - id: por
      style: docked
      contents:
        - href: por/index.Rmd
          text: Início
        - section: "Tutorial"
          contents:
            - por/tutorial/index.qmd
            - por/tutorial/00-funcoes.qmd
            - por/tutorial/01-download.qmd
            - por/tutorial/02-titulo.qmd
            - por/tutorial/03-resumo.qmd
            - por/tutorial/04-paciente-ideal.qmd
            - por/tutorial/05-patrocinador.qmd
            - por/tutorial/06-tipos-de-cancer.qmd
            - por/tutorial/07-subcondicoes.qmd
            - por/tutorial/08-identificador.qmd
            - por/tutorial/09-google-maps.qmd
            - por/tutorial/10-banco-de-dados.qmd
        - por/dados.qmd
    - id: eng
      style: docked
      contents:
        - href: eng/index.qmd
          text: Home
        - section: "Tutorial"
          contents:
            - eng/tutorial/index.qmd
            - eng/tutorial/00-helpers.qmd
            - eng/tutorial/01-download.qmd
            - eng/tutorial/02-title.qmd
            - eng/tutorial/03-summary.qmd
            - eng/tutorial/04-ideal-patient.qmd
            - eng/tutorial/05-sponsor.qmd
            - eng/tutorial/06-cancer-types.qmd
            - eng/tutorial/07-setting-biomarkers.qmd
            - eng/tutorial/08-location-id.qmd
            - eng/tutorial/09-google-maps.qmd
            - eng/tutorial/10-final-database.qmd
        - eng/data.qmd

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    code-copy: true
    include-in-header:
      - file: script.html
