title: "CancerTrialsBR"
description: "Plataforma Colaborativa de Estudos Clínicos em Oncologia"
theme: minima
baseurl: "/CancerTrialsBR" 
url: "https://felippelazar.github.io"
show_title: false

header_pages:
  - index.md
  - dados.md
  - pdfs.md
  - cni.md